version: '3.8'

services:
  chat:
    container_name: ssavice-chat
    image: hjinshin/ssavice-chat:latest
    ports:
      - "8080:8080" # EC2 8080 - 컨테이너 8080
    environment:
      KAFKA_SERVER_URL: ${KAFKA_SERVER_URL}
      CHAT_DB_URL: ${CHAT_DB_URL}
      CHAT_DB_USERNAME: ${CHAT_DB_USERNAME}
      CHAT_DB_PASSWORD: ${CHAT_DB_PASSWORD}
      CHAT_SERVER_ID: ${CHAT_SERVER_ID1}
      TZ: Asia/Seoul
    stop_grace_period: 30s
    # 항상 최신
    pull_policy: always