spring.application.name=Chat

spring.sql.init.mode=always

# Kafka
kafka.chat-topic=chat-topic
kafka.server-id=server-1

spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
spring.kafka.producer.acks=all
spring.kafka.producer.retries=3

spring.kafka.producer.properties.delivery.timeout.ms=120000
spring.kafka.producer.properties.request.timeout.ms=30000
spring.kafka.producer.properties.linger.ms=5
spring.kafka.producer.properties.batch.size=16384


spring.kafka.consumer.bootstrap-servers=localhost:9092
spring.kafka.consumer.auto-offset-reset=latest
spring.kafka.consumer.enable-auto-commit=false

spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer

spring.kafka.consumer.properties.spring.json.trusted.packages=*
spring.kafka.consumer.properties.spring.json.value.default.type=teamssavice.chat.model.ChatMessage

# R2dbc
spring.r2dbc.url=${CHAT_DB_URL}
spring.r2dbc.username=${CHAT_DB_USERNAME}
spring.r2dbc.password=${CHAT_DB_PASSWORD}
spring.r2dbc.pool.initial-size=5
spring.r2dbc.pool.max-size=20
